---
title: "Analysis"
author: "Mikhail Dozmorov"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: no
  html_document:
    theme: cerulean
    toc: yes
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
# Set up the environment
library(knitr)
opts_chunk$set(cache.path='cache/', fig.path='img/', cache=F, tidy=T, fig.keep='high', echo=F, dpi=100, warnings=F, message=F, comment=NA, warning=F, results='as.is', fig.width = 10, fig.height = 6) #out.width=700, 
library(pander)
panderOptions('table.split.table', Inf)
set.seed(1)
```

# Libraries

```{r libraries}
library(tidyverse)
library(readxl)
library(writexl)
library(cowplot)
library(stringr)
library("ggsci")
library(scales)
# scales::show_col(pal_lancet("lanonc")(8))
mycols = pal_lancet("lanonc")(8)
library(AnnotationHub)
library(ExperimentHub)
```

# Settings

```{r settings}
# Project folder path
dir_data <- ""

# Input files
fileNameIn1 <- file.path(dir_data, "")
# Output files
fileNameOut1 <- file.path(dir_data, "")
```

# AnnotationHub

```{r data}
ah <- AnnotationHub()
query_data <- query(ah, "CTCF")
query_data$dataprovider %>% table()
query_data$species %>% table()
query_data$genome %>% table()
query_data$coordinate_1_based %>% table()
query_data$sourcetype %>% table()

query_data_df <- data.frame(query_data$ah_id,
                            query_data$title,
                            query_data$dataprovider,
                            query_data$species,
                            query_data$taxonomyid,
                            query_data$genome,
                            query_data$description,
                            query_data$sourcetype)
# View(query_data_df)
```

# ExperimentHub

```{r data}
eh <- ExperimentHub()
query_data <- query(eh, "CTCF")
query_data$dataprovider %>% table()
query_data$species %>% table()
query_data$genome %>% table()
query_data$coordinate_1_based %>% table()
query_data$sourcetype %>% table()

query_data_df <- data.frame(query_data$ah_id,
                            query_data$title,
                            query_data$dataprovider,
                            query_data$species,
                            query_data$taxonomyid,
                            query_data$genome,
                            query_data$description,
                            query_data$sourcetype)
View(query_data_df)
```


